version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    stdin_open: true
    tty: true
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/cook-note
      # exclude volumes
      - /cook-note/tmp
      - /cook-note/log
      - /cook-note/.git
      - node_modules:/cook-note/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  mysql-data:
  node_modules: